# Working with Json

In [1]:
import pandas as pd

In [2]:
pd.read_json("train.json")

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
# load data from API 
pd.read_json("https://api.exchangerate-api.com/v4/latest/INR")

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-01-20,1768867201,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-01-20,1768867201,0.0404
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-01-20,1768867201,0.7240
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-01-20,1768867201,0.9140
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-01-20,1768867201,4.1800
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-01-20,1768867201,2.6200
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-01-20,1768867201,0.1810
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-01-20,1768867201,0.2210
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-01-20,1768867201,0.2820
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-01-20,1768867201,0.2820

# Working with SQL

1-firstlly we a software called XAMPP.

2-download this .

3-open XAAMOP control panel and start Apache(web server) and MYsql(database server).

4-Run this URL in your Machine localhost/phpmyadmin/.

5-Create a new database .

6-Now import the Sql file which you dowmload from kaggle.

7-Now we have to convert this into pandas dataframe.

8-install library - !pip install mysql.connector.

9- import mysql.connector

10-create a connection through python to your database
conn=mysql.connector.connect(host="localhost",user="root",password="",database="word")

pd.read_sql_query("Select * from city",conn)  # you write your code.

# Working with API

 * API- application programming interfaces.
 * in simple words Api a bridge or pipeline between two softwares .

In [5]:
import requests

response=requests.get("xyz ") # paste your API

response.json()["results"]  
* convert into the json formate
* want only the results column of this dataset

convert this json formate into dataframe
res=pd.DataFrame(response.json(['results'])

* extract the columns which you want .
res['x','y','z']

i am working in movies dataset so it has 428 pages so i will do this above work in loop to fetch the data from the api.

create empty dataframe

df=pd.Dataframe()

for i in range(1,429):
    response=response=requests.get("xyz ")
    temp_df=pd.Dataframe(response.json()["results"])[['x','y','z']]
    df=df.append(temp_df,ignore_index=True)

df.shape

df.to_csv("name of the dataset")

* rapid API - you can get free api to create the datasets.